2024-06-04 00:49:15,783:INFO:Snowflake Connector for Python Version: 3.10.1, Python Version: 3.12.3, Platform: Windows-11-10.0.22631-SP0
2024-06-04 00:49:15,783:INFO:This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
2024-06-04 00:49:18,102:INFO:Number of results in first chunk: 1
2024-06-04 00:49:18,528:INFO:Number of results in first chunk: 1
2024-06-04 00:49:18,764:INFO:Number of results in first chunk: 1
2024-06-04 00:49:19,141:INFO:Number of results in first chunk: 1
2024-06-04 00:49:19,314:INFO:Number of results in first chunk: 1
2024-06-04 00:49:19,598:INFO:Number of results in first chunk: 1
2024-06-04 00:49:19,787:INFO:Number of results in first chunk: 1
2024-06-04 00:49:20,054:INFO:Number of results in first chunk: 1
2024-06-04 00:49:20,353:INFO:Number of results in first chunk: 1
2024-06-04 00:49:20,589:INFO:Number of results in first chunk: 1
2024-06-04 00:49:20,856:INFO:Number of results in first chunk: 1
2024-06-04 00:49:20,950:INFO:Number of results in first chunk: 1
2024-06-04 00:49:20,950:INFO:closed
2024-06-04 00:49:21,029:INFO:No async queries seem to be running, deleting session
2024-06-04 00:49:21,108:INFO:DDL execution successful.
2024-06-21 19:10:26,582:INFO:Snowflake Connector for Python Version: 3.10.1, Python Version: 3.12.3, Platform: Windows-11-10.0.22631-SP0
2024-06-21 19:10:26,598:INFO:This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
2024-06-21 19:10:29,085:WARNING:Certificate did not match expected hostname: mcvpuud.yr28894.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
2024-06-21 19:10:29,085:WARNING:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(CertificateError("hostname 'mcvpuud.yr28894.snowflakecomputing.com' doesn't match either of '*.prod3.us-west-2.snowflakecomputing.com', '*.us-west-2.snowflakecomputing.com', '*.global.snowflakecomputing.com', '*.snowflakecomputing.com', '*.prod3.us-west-2.aws.snowflakecomputing.com'"))': /session/v1/login-request?request_id=3c049282-91d9-4866-b04b-a7de84b45984&databaseName=P01_EMP&schemaName=EMP_RAW&warehouse=COMPUTE_WH&request_guid=572d1225-05b2-485d-bc6f-7ee247f349ad
2024-06-21 19:10:30,154:WARNING:Certificate did not match expected hostname: mcvpuud.yr28894.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
2024-06-21 19:10:30,374:ERROR:Failed to get the response. Hanging? method: post, url: https://MCVPUUD.YR28894.snowflakecomputing.com:443/session/v1/login-request?request_id=3c049282-91d9-4866-b04b-a7de84b45984&databaseName=P01_EMP&schemaName=EMP_RAW&warehouse=COMPUTE_WH&request_guid=572d1225-05b2-485d-bc6f-7ee247f349ad, headers:{'Content-Type': 'application/json', 'accept': 'application/snowflake', 'User-Agent': 'PythonConnector/3.10.1 (Windows-11-10.0.22631-SP0) CPython/3.12.3', 'Content-Encoding': 'gzip'}, data: {"data": {"CLIENT_APP_ID": "PythonConnector", "CLIENT_APP_VERSION": "3.10.1", "SVN_REVISION": null, "ACCOUNT_NAME": "MCVPUUD", "LOGIN_NAME": "NISHITA27", "CLIENT_ENVIRONMENT": {"APPLICATION": "PythonConnector", "OS": "Windows", "OS_VERSION": "Windows-11-10.0.22631-SP0", "PYTHON_VERSION": "3.12.3", "PYTHON_RUNTIME": "CPython", "PYTHON_COMPILER": "MSC v.1938 64 bit (AMD64)", "OCSP_MODE": "FAIL_OPEN", "TRACING": 20, "LOGIN_TIMEOUT": null, "NETWORK_TIMEOUT": null, "SOCKET_TIMEOUT": null}, "PASSWORD": "**** "SESSION_PARAMETERS": {"CLIENT_PREFETCH_THREADS": 4}}}
2024-06-21 19:10:32,842:WARNING:Certificate did not match expected hostname: mcvpuud.yr28894.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
2024-06-21 19:10:32,842:WARNING:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(CertificateError("hostname 'mcvpuud.yr28894.snowflakecomputing.com' doesn't match either of '*.prod3.us-west-2.snowflakecomputing.com', '*.us-west-2.snowflakecomputing.com', '*.global.snowflakecomputing.com', '*.snowflakecomputing.com', '*.prod3.us-west-2.aws.snowflakecomputing.com'"))': /session/v1/login-request?request_id=d1473794-7580-402d-a52b-29f502f7118c&databaseName=P01_EMP&schemaName=EMP_RAW&warehouse=COMPUTE_WH&request_guid=3312ae30-fabd-44be-8250-16b1e9742cfd
2024-06-21 19:10:34,051:WARNING:Certificate did not match expected hostname: mcvpuud.yr28894.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
2024-06-21 19:10:34,051:ERROR:Failed to get the response. Hanging? method: post, url: https://MCVPUUD.YR28894.snowflakecomputing.com:443/session/v1/login-request?request_id=d1473794-7580-402d-a52b-29f502f7118c&databaseName=P01_EMP&schemaName=EMP_RAW&warehouse=COMPUTE_WH&request_guid=3312ae30-fabd-44be-8250-16b1e9742cfd, headers:{'Content-Type': 'application/json', 'accept': 'application/snowflake', 'User-Agent': 'PythonConnector/3.10.1 (Windows-11-10.0.22631-SP0) CPython/3.12.3', 'Content-Encoding': 'gzip'}, data: {"data": {"CLIENT_APP_ID": "PythonConnector", "CLIENT_APP_VERSION": "3.10.1", "SVN_REVISION": null, "ACCOUNT_NAME": "MCVPUUD", "LOGIN_NAME": "NISHITA27", "CLIENT_ENVIRONMENT": {"APPLICATION": "PythonConnector", "OS": "Windows", "OS_VERSION": "Windows-11-10.0.22631-SP0", "PYTHON_VERSION": "3.12.3", "PYTHON_RUNTIME": "CPython", "PYTHON_COMPILER": "MSC v.1938 64 bit (AMD64)", "OCSP_MODE": "FAIL_OPEN", "TRACING": 20, "LOGIN_TIMEOUT": null, "NETWORK_TIMEOUT": null, "SOCKET_TIMEOUT": null}, "PASSWORD": "**** "SESSION_PARAMETERS": {"CLIENT_PREFETCH_THREADS": 4}}}
2024-06-21 19:10:34,083:ERROR:Error executing DDL: 250001: 250001: Could not connect to Snowflake backend after 2 attempt(s).Aborting
2024-06-21 19:11:12,331:INFO:Snowflake Connector for Python Version: 3.10.1, Python Version: 3.12.3, Platform: Windows-11-10.0.22631-SP0
2024-06-21 19:11:12,331:INFO:This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
2024-06-21 19:11:13,904:WARNING:Certificate did not match expected hostname: mcvpuud.yr28894.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
2024-06-21 19:11:13,920:WARNING:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(CertificateError("hostname 'mcvpuud.yr28894.snowflakecomputing.com' doesn't match either of '*.prod3.us-west-2.snowflakecomputing.com', '*.us-west-2.snowflakecomputing.com', '*.global.snowflakecomputing.com', '*.snowflakecomputing.com', '*.prod3.us-west-2.aws.snowflakecomputing.com'"))': /session/v1/login-request?request_id=be3cfb65-c49a-4657-91aa-e95ac3c9eb99&databaseName=P01_EMP&schemaName=EMP_RAW&warehouse=COMPUTE_WH&request_guid=ed8b8c3e-0edc-4099-a702-05ce4399fbbc
2024-06-21 19:11:14,879:WARNING:Certificate did not match expected hostname: mcvpuud.yr28894.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
2024-06-21 19:11:14,895:ERROR:Failed to get the response. Hanging? method: post, url: https://MCVPUUD.YR28894.snowflakecomputing.com:443/session/v1/login-request?request_id=be3cfb65-c49a-4657-91aa-e95ac3c9eb99&databaseName=P01_EMP&schemaName=EMP_RAW&warehouse=COMPUTE_WH&request_guid=ed8b8c3e-0edc-4099-a702-05ce4399fbbc, headers:{'Content-Type': 'application/json', 'accept': 'application/snowflake', 'User-Agent': 'PythonConnector/3.10.1 (Windows-11-10.0.22631-SP0) CPython/3.12.3', 'Content-Encoding': 'gzip'}, data: {"data": {"CLIENT_APP_ID": "PythonConnector", "CLIENT_APP_VERSION": "3.10.1", "SVN_REVISION": null, "ACCOUNT_NAME": "MCVPUUD", "LOGIN_NAME": "NISHITA27", "CLIENT_ENVIRONMENT": {"APPLICATION": "PythonConnector", "OS": "Windows", "OS_VERSION": "Windows-11-10.0.22631-SP0", "PYTHON_VERSION": "3.12.3", "PYTHON_RUNTIME": "CPython", "PYTHON_COMPILER": "MSC v.1938 64 bit (AMD64)", "OCSP_MODE": "FAIL_OPEN", "TRACING": 20, "LOGIN_TIMEOUT": null, "NETWORK_TIMEOUT": null, "SOCKET_TIMEOUT": null}, "PASSWORD": "**** "SESSION_PARAMETERS": {"CLIENT_PREFETCH_THREADS": 4}}}
2024-06-21 19:11:16,576:WARNING:Certificate did not match expected hostname: mcvpuud.yr28894.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
2024-06-21 19:11:16,576:WARNING:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(CertificateError("hostname 'mcvpuud.yr28894.snowflakecomputing.com' doesn't match either of '*.prod3.us-west-2.snowflakecomputing.com', '*.us-west-2.snowflakecomputing.com', '*.global.snowflakecomputing.com', '*.snowflakecomputing.com', '*.prod3.us-west-2.aws.snowflakecomputing.com'"))': /session/v1/login-request?request_id=2bdc08b9-77f1-4364-b91d-71588635ed75&databaseName=P01_EMP&schemaName=EMP_RAW&warehouse=COMPUTE_WH&request_guid=4f4c8853-bb9f-44a1-9d91-d590d8a05994
2024-06-21 19:11:17,880:WARNING:Certificate did not match expected hostname: mcvpuud.yr28894.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
2024-06-21 19:11:17,896:ERROR:Failed to get the response. Hanging? method: post, url: https://MCVPUUD.YR28894.snowflakecomputing.com:443/session/v1/login-request?request_id=2bdc08b9-77f1-4364-b91d-71588635ed75&databaseName=P01_EMP&schemaName=EMP_RAW&warehouse=COMPUTE_WH&request_guid=4f4c8853-bb9f-44a1-9d91-d590d8a05994, headers:{'Content-Type': 'application/json', 'accept': 'application/snowflake', 'User-Agent': 'PythonConnector/3.10.1 (Windows-11-10.0.22631-SP0) CPython/3.12.3', 'Content-Encoding': 'gzip'}, data: {"data": {"CLIENT_APP_ID": "PythonConnector", "CLIENT_APP_VERSION": "3.10.1", "SVN_REVISION": null, "ACCOUNT_NAME": "MCVPUUD", "LOGIN_NAME": "NISHITA27", "CLIENT_ENVIRONMENT": {"APPLICATION": "PythonConnector", "OS": "Windows", "OS_VERSION": "Windows-11-10.0.22631-SP0", "PYTHON_VERSION": "3.12.3", "PYTHON_RUNTIME": "CPython", "PYTHON_COMPILER": "MSC v.1938 64 bit (AMD64)", "OCSP_MODE": "FAIL_OPEN", "TRACING": 20, "LOGIN_TIMEOUT": null, "NETWORK_TIMEOUT": null, "SOCKET_TIMEOUT": null}, "PASSWORD": "**** "SESSION_PARAMETERS": {"CLIENT_PREFETCH_THREADS": 4}}}
2024-06-21 19:11:17,896:ERROR:Error executing DDL: 250001: 250001: Could not connect to Snowflake backend after 2 attempt(s).Aborting
2024-06-21 19:14:27,156:INFO:Snowflake Connector for Python Version: 3.10.1, Python Version: 3.12.3, Platform: Windows-11-10.0.22631-SP0
2024-06-21 19:14:27,156:INFO:This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
2024-06-21 19:14:28,744:WARNING:Certificate did not match expected hostname: mcvpuud.yr28894.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
2024-06-21 19:14:28,744:WARNING:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(CertificateError("hostname 'mcvpuud.yr28894.snowflakecomputing.com' doesn't match either of '*.prod3.us-west-2.snowflakecomputing.com', '*.us-west-2.snowflakecomputing.com', '*.global.snowflakecomputing.com', '*.snowflakecomputing.com', '*.prod3.us-west-2.aws.snowflakecomputing.com'"))': /session/v1/login-request?request_id=f5eaef4b-d841-4c43-9a71-4df8c6c4670a&databaseName=P01_EMP&schemaName=EMP_RAW&warehouse=COMPUTE_WH&request_guid=61085f98-36cf-40fb-800c-f6769c8df368
2024-06-21 19:14:29,764:WARNING:Certificate did not match expected hostname: mcvpuud.yr28894.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
2024-06-21 19:14:29,780:ERROR:Failed to get the response. Hanging? method: post, url: https://MCVPUUD.YR28894.snowflakecomputing.com:443/session/v1/login-request?request_id=f5eaef4b-d841-4c43-9a71-4df8c6c4670a&databaseName=P01_EMP&schemaName=EMP_RAW&warehouse=COMPUTE_WH&request_guid=61085f98-36cf-40fb-800c-f6769c8df368, headers:{'Content-Type': 'application/json', 'accept': 'application/snowflake', 'User-Agent': 'PythonConnector/3.10.1 (Windows-11-10.0.22631-SP0) CPython/3.12.3', 'Content-Encoding': 'gzip'}, data: {"data": {"CLIENT_APP_ID": "PythonConnector", "CLIENT_APP_VERSION": "3.10.1", "SVN_REVISION": null, "ACCOUNT_NAME": "MCVPUUD", "LOGIN_NAME": "NISHITA27", "CLIENT_ENVIRONMENT": {"APPLICATION": "PythonConnector", "OS": "Windows", "OS_VERSION": "Windows-11-10.0.22631-SP0", "PYTHON_VERSION": "3.12.3", "PYTHON_RUNTIME": "CPython", "PYTHON_COMPILER": "MSC v.1938 64 bit (AMD64)", "OCSP_MODE": "FAIL_OPEN", "TRACING": 20, "LOGIN_TIMEOUT": null, "NETWORK_TIMEOUT": null, "SOCKET_TIMEOUT": null}, "PASSWORD": "**** "SESSION_PARAMETERS": {"CLIENT_PREFETCH_THREADS": 4}}}
2024-06-21 19:14:31,726:WARNING:Certificate did not match expected hostname: mcvpuud.yr28894.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
2024-06-21 19:14:31,730:WARNING:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(CertificateError("hostname 'mcvpuud.yr28894.snowflakecomputing.com' doesn't match either of '*.prod3.us-west-2.snowflakecomputing.com', '*.us-west-2.snowflakecomputing.com', '*.global.snowflakecomputing.com', '*.snowflakecomputing.com', '*.prod3.us-west-2.aws.snowflakecomputing.com'"))': /session/v1/login-request?request_id=08e63b86-363d-42b7-8d2f-39f2fa17a5e9&databaseName=P01_EMP&schemaName=EMP_RAW&warehouse=COMPUTE_WH&request_guid=39f2ac51-99f3-4cd3-88c8-7180f421b9e1
2024-06-21 19:14:32,924:WARNING:Certificate did not match expected hostname: mcvpuud.yr28894.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}
2024-06-21 19:14:32,924:ERROR:Failed to get the response. Hanging? method: post, url: https://MCVPUUD.YR28894.snowflakecomputing.com:443/session/v1/login-request?request_id=08e63b86-363d-42b7-8d2f-39f2fa17a5e9&databaseName=P01_EMP&schemaName=EMP_RAW&warehouse=COMPUTE_WH&request_guid=39f2ac51-99f3-4cd3-88c8-7180f421b9e1, headers:{'Content-Type': 'application/json', 'accept': 'application/snowflake', 'User-Agent': 'PythonConnector/3.10.1 (Windows-11-10.0.22631-SP0) CPython/3.12.3', 'Content-Encoding': 'gzip'}, data: {"data": {"CLIENT_APP_ID": "PythonConnector", "CLIENT_APP_VERSION": "3.10.1", "SVN_REVISION": null, "ACCOUNT_NAME": "MCVPUUD", "LOGIN_NAME": "NISHITA27", "CLIENT_ENVIRONMENT": {"APPLICATION": "PythonConnector", "OS": "Windows", "OS_VERSION": "Windows-11-10.0.22631-SP0", "PYTHON_VERSION": "3.12.3", "PYTHON_RUNTIME": "CPython", "PYTHON_COMPILER": "MSC v.1938 64 bit (AMD64)", "OCSP_MODE": "FAIL_OPEN", "TRACING": 20, "LOGIN_TIMEOUT": null, "NETWORK_TIMEOUT": null, "SOCKET_TIMEOUT": null}, "PASSWORD": "**** "SESSION_PARAMETERS": {"CLIENT_PREFETCH_THREADS": 4}}}
2024-06-21 19:14:32,924:ERROR:Error executing DDL: 250001: 250001: Could not connect to Snowflake backend after 2 attempt(s).Aborting
2024-06-21 19:21:15,427:INFO:Snowflake Connector for Python Version: 3.10.1, Python Version: 3.12.3, Platform: Windows-11-10.0.22631-SP0
2024-06-21 19:21:15,427:INFO:This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
2024-06-21 19:21:17,883:INFO:Number of results in first chunk: 1
2024-06-21 19:21:23,446:INFO:Number of results in first chunk: 1
2024-06-21 19:21:23,638:INFO:Number of results in first chunk: 1
2024-06-21 19:21:23,995:INFO:Number of results in first chunk: 1
2024-06-21 19:21:24,231:INFO:Number of results in first chunk: 1
2024-06-21 19:21:24,498:INFO:Number of results in first chunk: 1
2024-06-21 19:21:24,812:INFO:Number of results in first chunk: 1
2024-06-21 19:21:24,985:INFO:Number of results in first chunk: 1
2024-06-21 19:21:25,314:INFO:Number of results in first chunk: 1
2024-06-21 19:21:25,627:INFO:Number of results in first chunk: 1
2024-06-21 19:21:26,318:INFO:Number of results in first chunk: 1
2024-06-21 19:21:26,474:INFO:Number of results in first chunk: 1
2024-06-21 19:21:26,483:INFO:closed
2024-06-21 19:21:26,553:INFO:No async queries seem to be running, deleting session
2024-06-21 19:21:26,638:INFO:DDL execution successful.
